from abc import ABC, abstractmethod


class BrokerAdapter(ABC):
    @abstractmethod
    def get_price(self): ...
    @abstractmethod
    def get_account(self): ...
    @abstractmethod
    def open_position(self, order): ...
    @abstractmethod
    def close_position(self, trade_id): ...
    @abstractmethod
    def modify_position(self, trade_id, stop_loss, take_profit): ...
